### PR TITLE
Avoid closure in @safe_* macros

### LINKED ISSUE #685: Safe logging macros don't work in generated functions due to `with_logger` closure
This is my fault, ref https://github.com/JuliaGPU/GPUCompiler.jl/pull/622

MWE:

```julia-repl
julia> using GPUCompiler

julia> @generated function trywarn()
           return :(GPUCompiler.@safe_warn "watch out!")
       end
trywarn (generic function with 1 method)

julia> trywarn()
ERROR: The function body AST defined by this @generated function is not pure. This likely means it contains a closure, a comprehension or a generator.
Stacktrace:
 [1] top-level scope
   @ REPL[5]:1
```

The problem is there's no public closure-free API to change the _current_ logger. The non-public way is to reassign `current_task().logstate`, which is what `with_logger` does under the hood.

So I guess the choices are
* Copy the internals of `with_logger`, i.e., reassign the non-public `current_task().logstate`
* Revert to mutating the global logger and hope that `@safe_*` is never used in a task that's attached to a non-global logger

### PR DESCRIPTION
**Pull request by danielwe**
Fixes #685 

I noticed the testing of these macros was nuked in #658, so I didn't add any tests here, but I'm happy to add something akin to the #685 MWE if desired.

### CODE REVIEW

**Comment by danielwe** [comment]
Oh shoot, this solution only works on 1.10. The implementation was reworked to use ScopedValues for 1.11. That's why you don't try to rely on non-public API I guess. Any suggestions for a better way, @vchuravy?

**Comment by danielwe** [comment]
This is ready for review if you're interested. AMDGPU.jl failures look unrelated. Looks like all the recent green commits skipped these tests due to unsatisfiable requirements.

File: src/utils.jl [hunk 1]
```diff
@@ -69,9 +87,9 @@ for level in [:debug, :info, :warn, :error]
                 # they may expect Logging.shouldlog() getting called, so we use
                 # the global_logger()'s min level which is more likely to be usable.
                 min_level = _invoked_min_enabled_level(global_logger())
-                with_logger(Logging.ConsoleLogger(io, min_level)) do
-                    $(esc(macrocall))
-                end
+                safe_logger = Logging.ConsoleLogger(io, min_level)
+                safe_logstate = Base.CoreLogging.LogState(safe_logger)
+                @safe_with_logstate safe_logstate $(esc(macrocall))
```
Comment (maleadt) [inline src/utils.jl:92]: Why a secondary macro, and not inline the definition here?

If the macro is needed, I think it's also better to do `$GPUCompiler.@safe_with_logstate` to support use of these macros from outside GPUCompiler.jl.

Comment (danielwe) [reply src/utils.jl:92]: No it could totally go inline, it just felt cleaner this way, but I didn't think about the scoping issue when used outside GPUCompiler. Will push an update putting it inline.

**Review by maleadt — APPROVED** [review]
Thanks!
