### PR TITLE
irgen: Disable fn entry safepoints

### LINKED ISSUE #364: Adapt to function entry safepoint changes
Presumably as a result of https://github.com/JuliaLang/julia/pull/41616 being merged, nightly CI for CUDA and AMDGPU is failing with calls to `julia.get_pgcstack`. We need to now disable this codegen feature, named `safepoint_on_entry`.

### PR DESCRIPTION
**Pull request by jpsamaroo**
Fixes #364

### CODE REVIEW

**Comment by maleadt** [comment]
Maybe use a NamedTuple or Dict you conditionally append the new parameter to, and splat that when calling the CodegenParams ctor, just to avoid some duplication. But LGTM otherwise.

**Comment by pxl-th** [comment]
Can we also tag a release to fix crashing CIs?

File: src/jlgen.jl [hunk 1]
```diff
@@ -361,13 +361,17 @@ function compile_method_instance(@nospecialize(job::CompilerJob),
...
-    params = Base.CodegenParams(;
+    cgparams = (;
         track_allocations  = false,
         code_coverage      = false,
         prefer_specsig     = true,
         gnu_pubnames       = false,
         debug_info_kind    = Cint(debug_info_kind),
         lookup             = Base.unsafe_convert(Ptr{Nothing}, lookup_cb))
+    @static if VERSION >= v"1.9.0-DEV.1660"
+        cgparams = merge(cgparams, (;safepoint_on_entry = false))
```
Comment (vchuravy) [inline src/jlgen.jl:372]: Nit, this is not high-priority. But the CPU users like Enzyme would actually want these to be emitted. So it needs to be job-dependent.
